config/routes.rb
Rails.application.routes.draw do
  resources :engineers

  resources :proyects

  resources :proyects do
    resources :engineers
  end

end

app/models/engineer.rb
class Engineer < ActiveRecord::Base
  belongs_to :proyect
end

app/models/name.rb
class Name < ActiveRecord::Base
end

app/models/person.rb
class Person < ActiveRecord::Base
end

app/models/proyect.rb
class Proyect < ActiveRecord::Base
	has_many:engineers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/engineers_controller.rb
class EngineersController < ApplicationController
  before_action :set_engineer, only: [:show, :edit, :update, :destroy, :index, :new, :create]

  # GET /engineers
  # GET /engineers.json
  def index
    @engineers =  @proyect.engineers.all # lista solo los ingenieros de ese proyecto no todos
  end

  # GET /engineers/1
  # GET /engineers/1.json
  def show
  end

  # GET /engineers/new
  def new
    @engineer = Engineer.new
  end

  # GET /engineers/1/edit
  def edit
  end

  # POST /engineers
  # POST /engineers.json
  def create
    @engineer = Engineer.new(engineer_params)
    @engineer.proyect_id = @proyect.id
    respond_to do |format|
      if @engineer.save
        format.html { redirect_to proyect_engineers_path(@proyect), notice: 'Engineer was successfully created.' }
        format.json { render :show, status: :created, location: @engineer }
      else
        format.html { render :new }
        format.json { render json: @engineer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /engineers/1
  # PATCH/PUT /engineers/1.json
  def update
    respond_to do |format|
      if @engineer.update(engineer_params)
        format.html { redirect_to proyect_engineers_path(@proyect), notice: 'Engineer was successfully updated.' }
        format.json { render :show, status: :ok, location: @engineer }
      else
        format.html { render :edit }
        format.json { render json: @engineer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /engineers/1
  # DELETE /engineers/1.json
  def destroy
    @engineer.destroy
    respond_to do |format|
      format.html { redirect_to proyect_engineers_url(@proyect), notice: 'Engineer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_engineer
      @proyect = Proyect.find(params[:proyect_id]) # recupera el proyecto
      @engineer = Engineer.find(params[:id])if params[:id] # recupera el id solo si lo envian
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def engineer_params
      params.require(:engineer).permit(:fullname, :dependency, :studies, :proyect_id)
    end
end

app/controllers/names_controller.rb
class NamesController < ApplicationController
  before_action :set_name, only: [:show, :edit, :update, :destroy]

  # GET /names
  # GET /names.json
  def index
    @names = Name.all
  end

  # GET /names/1
  # GET /names/1.json
  def show
  end

  # GET /names/new
  def new
    @name = Name.new
  end

  # GET /names/1/edit
  def edit
  end

  # POST /names
  # POST /names.json
  def create
    @name = Name.new(name_params)

    respond_to do |format|
      if @name.save
        format.html { redirect_to @name, notice: 'Name was successfully created.' }
        format.json { render :show, status: :created, location: @name }
      else
        format.html { render :new }
        format.json { render json: @name.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /names/1
  # PATCH/PUT /names/1.json
  def update
    respond_to do |format|
      if @name.update(name_params)
        format.html { redirect_to @name, notice: 'Name was successfully updated.' }
        format.json { render :show, status: :ok, location: @name }
      else
        format.html { render :edit }
        format.json { render json: @name.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /names/1
  # DELETE /names/1.json
  def destroy
    @name.destroy
    respond_to do |format|
      format.html { redirect_to names_url, notice: 'Name was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_name
      @name = Name.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def name_params
      params[:name]
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :description, :begindate, :enddate)
    end
end

app/controllers/proyects_controller.rb
class ProyectsController < ApplicationController
  before_action :set_proyect, only: [:show, :edit, :update, :destroy]

  # GET /proyects
  # GET /proyects.json
  def index
    @proyects = Proyect.all
  end

  # GET /proyects/1
  # GET /proyects/1.json
  def show
  end

  # GET /proyects/new
  def new
    @proyect = Proyect.new
  end

  # GET /proyects/1/edit
  def edit
  end

  # POST /proyects
  # POST /proyects.json
  def create
    @proyect = Proyect.new(proyect_params)

    respond_to do |format|
      if @proyect.save
        format.html { redirect_to @proyect, notice: 'Proyect was successfully created.' }
        format.json { render :show, status: :created, location: @proyect }
      else
        format.html { render :new }
        format.json { render json: @proyect.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proyects/1
  # PATCH/PUT /proyects/1.json
  def update
    respond_to do |format|
      if @proyect.update(proyect_params)
        format.html { redirect_to @proyect, notice: 'Proyect was successfully updated.' }
        format.json { render :show, status: :ok, location: @proyect }
      else
        format.html { render :edit }
        format.json { render json: @proyect.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proyects/1
  # DELETE /proyects/1.json
  def destroy
    @proyect.destroy
    respond_to do |format|
      format.html { redirect_to proyects_url, notice: 'Proyect was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proyect
      @proyect = Proyect.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def proyect_params
      params.require(:proyect).permit(:name, :description, :begindate, :enddate)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/engineers_helper.rb
module EngineersHelper
end

app/helpers/names_helper.rb
module NamesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/proyects_helper.rb
module ProyectsHelper
end

app/views/engineers/_form.html.erb
<%= simple_form_for [@proyect,@engineer], :html => { :class => 'form-vertical' } do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :fullname %>
    <%= f.input :dependency %>
    <%= f.input :studies %>
    <%= f.association :proyect %>
  </div>

  <div class="form-actions">
    <%= f.button :submit,:class => 'btn-primary'%>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
              proyect_engineers_path(@proyect), :class => 'btn' %>
  </div>

<% end %>

app/views/engineers/edit.html.erb
<h1>Editing engineer</h1>

<%= render 'form' %>

<%= link_to 'Show', @engineer %> |
<%= link_to 'Back', engineers_path %>

app/views/engineers/index.html.erb
<h1>Listing engineers</h1>

<table>
  <thead>
    <tr>
      <th>Fullname</th>
      <th>Dependency</th>
      <th>Studies</th>
      <th>Proyect</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @engineers.each do |engineer| %>
      <tr>
        <td><%= engineer.fullname %></td>
        <td><%= engineer.dependency %></td>
        <td><%= engineer.studies %></td>
        <td><%= engineer.proyect.name %></td>
    
        <%= link_to t('.Edit',:default  => t("helpers.links.edit")),edit_proyect_engineer_path(@proyect,engineer), :class => 'btn btn-danger' %>
       
       <%= link_to t('.destroy',:default  => t("helpers.links.destroy")),proyect_engineer_path(@proyect,engineer), :method => :delete,:data => {:confirm => t('.confirm',:default => t("helpers.links.confirm", :default =>'Are you sure?'))},:class => 'btn btn-danger' %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('.new', :default => t("helpers.links.new")),
          new_proyect_engineer_path(@proyect),
          :class => 'btn btn-primary' %>

app/views/engineers/new.html.erb
<h1>New engineer</h1>

<%= render 'form' %>

<%= link_to 'Back', engineers_path %>

app/views/engineers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fullname:</strong>
  <%= @engineer.fullname %>
</p>

<p>
  <strong>Dependency:</strong>
  <%= @engineer.dependency %>
</p>

<p>
  <strong>Studies:</strong>
  <%= @engineer.studies %>
</p>

<p>
  <strong>Proyect:</strong>
  <%= @engineer.proyect %>
</p>

<%= link_to t('.Edit',:default  => t("helpers.links.edit")),edit_engineer_path(engineer), :class => 'btn btn-primary' %> |

<%= link_to t('.Back',:default  => t("helpers.links.back")),engineer_path(engineer), :class => 'btn btn-primary'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ror4x</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/people/_form.html.erb
<%= simple_form_for @person, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :begindate %>
  <%= f.input :enddate %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                people_path, :class => 'btn' %>
  </div>
<% end %>

app/views/people/edit.html.erb
<%- model_class = Person -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/people/index.html.erb
<%- model_class = Person -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:begindate) %></th>
      <th><%= model_class.human_attribute_name(:enddate) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= link_to person.id, person_path(person) %></td>
        <td><%= person.name %></td>
        <td><%= person.description %></td>
        <td><%= person.begindate %></td>
        <td><%= person.enddate %></td>
        <td><%=l person.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_person_path(person), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      person_path(person),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_person_path,
            :class => 'btn btn-primary' %>

app/views/people/new.html.erb
<%- model_class = Person -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/people/show.html.erb
<%- model_class = Person -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @person.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @person.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:begindate) %>:</strong></dt>
  <dd><%= @person.begindate %></dd>
  <dt><strong><%= model_class.human_attribute_name(:enddate) %>:</strong></dt>
  <dd><%= @person.enddate %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              people_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_person_path(@person), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              person_path(@person),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/proyects/_form.html.erb
<%= simple_form_for(@proyect) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :begindate %>
    <%= f.input :enddate %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/proyects/edit.html.erb
<h1>Editing proyect</h1>

<%= render 'form' %>

<%= link_to 'Show', @proyect %> |
<%= link_to 'Back', proyects_path %>

app/views/proyects/index.html.erb
<h1>Listing proyects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Begindate</th>
      <th>Enddate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @proyects.each do |proyect| %>
      <tr>
        <td><%= link_to 'Equipo',proyect_engineers_path(proyect) %></td>
        <td><%= proyect.name %></td>
        <td><%= proyect.description %></td>
        <td><%= proyect.begindate %></td>
        <td><%= proyect.enddate %></td>
        <td><%= link_to 'Show', proyect %></td>
        <td><%= link_to 'Edit', edit_proyect_path(proyect) %></td>
        <td><%= link_to 'Destroy', proyect, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Proyect', new_proyect_path %>

app/views/proyects/new.html.erb
<h1>New proyect</h1>

<%= render 'form' %>

<%= link_to 'Back', proyects_path %>

app/views/proyects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @proyect.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @proyect.description %>
</p>

<p>
  <strong>Begindate:</strong>
  <%= @proyect.begindate %>
</p>

<p>
  <strong>Enddate:</strong>
  <%= @proyect.enddate %>
</p>

<%= link_to 'Edit', edit_proyect_path(@proyect) %> |
<%= link_to 'Back', proyects_path %>